//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Madrinha
    {
        public int MadrinhaID { get; set; }
        public string Nome { get; set; }
        public string Conhecimentos { get; set; }
        public string Localizacao { get; set; }
        public string Horario { get; set; }
        public string Interesses { get; set; }
    }
}
